const Map<String, String> arStrings = {
  'appTitle': 'الملف الشخصي',
  'navHome': 'الرئيسية',
  'navAbout': 'نبذة',
  'navSkills': 'المهارات',
  'navProjects': 'المشاريع',
  'navContact': 'تواصل',
  'homeName': 'محمد ناتور',
  'homeTitle': 'مهندس حاسوب',
  'homeTagline': 'أبني منتجات موبايل وويب موثوقة بهندسة نظيفة وتأثير واضح.',
  'homeHighlightExperience': 'أكثر من 4 سنوات خبرة',
  'homeHighlightArchitecture': 'هندسة نظيفة',
  'homeHighlightDelivery': 'تسليم متعدد المنصات',
  'homeStatusTitle': 'متاح لمشاريع جديدة',
  'homeStatusBody': 'متاح لفرص عمل حر أو بدوام كامل في Flutter و React Native.',
  'homeStatusTimeZone': 'التوقيت GMT+2',
  'aboutTitle': 'نبذة عني',
  'aboutBody':
      'أتخصص في Flutter و React Native لبناء تجارب متعددة المنصات بسرعة وأناقة. '
      'في الخلفية، أبني خدمات قابلة للتوسع باستخدام Laravel و Firebase (Google). '
      'نهجي يرتكز على حل المشكلات، والهندسة النظيفة، وقابلية الصيانة.',
  'skillsTitle': 'المهارات',
  'skillFlutter': 'Flutter',
  'skillReactNative': 'React Native',
  'skillLaravel': 'Laravel',
  'skillFirebase': 'Firebase',
  'skillRestApis': 'واجهات REST',
  'skillProblemSolving': 'حل المشكلات',
  'projectsTitle': 'المشاريع',
  'projectsLoading': 'جاري تحميل المشاريع...',
  'projectsEmpty': 'لا توجد مشاريع بعد. سيتم عرض أمثلة.',
  'projectFallbackTitleOne': 'FlowPay Wallet',
  'projectFallbackDescOne':
      'تجربة محفظة مالية آمنة مع تحديثات فورية للرصيد وتسجيل سلس.',
  'projectFallbackTechOne': 'Flutter · Firebase · Stripe',
  'projectFallbackTitleTwo': 'Clinic Connect',
  'projectFallbackDescTwo':
      'جدولة المواعيد ومتابعة المرضى مع صلاحيات متعددة وتحليلات.',
  'projectFallbackTechTwo': 'Flutter · Laravel · MySQL',
  'projectFallbackTitleThree': 'Retail Pulse',
  'projectFallbackDescThree':
      'لوحة مخزون ومبيعات مع مزامنة تعمل دون اتصال للفرق الميدانية.',
  'projectFallbackTechThree': 'React Native · Firebase · REST APIs',
  'contactTitle': 'تواصل',
  'contactGithub': 'جيت هاب',
  'contactLinkedIn': 'لينكدإن',
  'contactWhatsApp': 'واتساب',
  'footerNote': 'لنصنع شيئًا مميزًا معًا.',
};
