const Map<String, String> enStrings = {
  'appTitle': 'Portfolio',
  'navHome': 'Home',
  'navAbout': 'About',
  'navSkills': 'Skills',
  'navProjects': 'Projects',
  'navContact': 'Contact',
  'homeName': 'Mohammad Natour',
  'homeTitle': 'Computer Engineer',
  'homeTagline': 'Building reliable mobile and web products with clean architecture and impact.',
  'homeHighlightExperience': '4+ Years Experience',
  'homeHighlightArchitecture': 'Clean Architecture',
  'homeHighlightDelivery': 'Cross-Platform Delivery',
  'homeStatusTitle': 'Available for new projects',
  'homeStatusBody': 'Open to freelance and full-time opportunities in Flutter and React Native.',
  'homeStatusTimeZone': 'Based in GMT+2',
  'aboutTitle': 'About Me',
  'aboutBody':
      'I specialize in Flutter and React Native, delivering responsive and polished cross-platform experiences. '
      'On the backend, I build scalable services with Laravel and Firebase (Google). '
      'My approach emphasizes problem solving, clean architecture, and maintainable codebases.',
  'skillsTitle': 'Skills',
  'skillFlutter': 'Flutter',
  'skillReactNative': 'React Native',
  'skillLaravel': 'Laravel',
  'skillFirebase': 'Firebase',
  'skillRestApis': 'REST APIs',
  'skillProblemSolving': 'Problem Solving',
  'projectsTitle': 'Projects',
  'projectsLoading': 'Loading projects...',
  'projectsEmpty': 'No projects found yet. Showing curated examples.',
  'projectFallbackTitleOne': 'FlowPay Wallet',
  'projectFallbackDescOne':
      'A secure fintech wallet experience with real-time balance updates and smooth onboarding.',
  'projectFallbackTechOne': 'Flutter · Firebase · Stripe',
  'projectFallbackTitleTwo': 'Clinic Connect',
  'projectFallbackDescTwo':
      'Appointment scheduling and patient tracking with role-based access and analytics.',
  'projectFallbackTechTwo': 'Flutter · Laravel · MySQL',
  'projectFallbackTitleThree': 'Retail Pulse',
  'projectFallbackDescThree':
      'Inventory and sales dashboard with offline-first sync for field teams.',
  'projectFallbackTechThree': 'React Native · Firebase · REST APIs',
  'contactTitle': 'Contact',
  'contactGithub': 'GitHub',
  'contactLinkedIn': 'LinkedIn',
  'contactWhatsApp': 'WhatsApp',
  'footerNote': 'Let’s create something remarkable together.',
};
